#!/bin/bash
#script to illustrate for loop
#
if [ $# -eq 0 ]
  then
  echo "Error - command line argument must be a number"
  echo "Syntax : $0 number"
  echo "Use to print multiplicatin tabel for given number"
  exit 1
fi

n=$1

for i in 1 2 3 4 5 6 7 8 9 10
  do
    echo "$n * $i = `expr $i \* $n`"
done

##you can also run forloops this way##
echo "another example of for loops"

for (( i = 0 ; i <= 5; i++ ))
do
  echo "Welcome $i times"
done

