#!/bin/bash
#how to handle user inputs with the 'read' statement
clear
echo "Enter your first name: "
read fname
echo "Enter your last name: "
read lname
echo "Hello $fname $lname, glad to meet you"

