#!/bin/bash
# if-then-else multilevel statements
#
if [ $1 -gt 0 ]
  then
  echo "$1 is positive"
elif [ $1 -lt 0 ]
  then
  echo "$1 is negative"
else
  echo "Oops! $1 is not a number. This script requires an integer"
fi
