#!/bin/bash
#
#script to see if an integer is pos or neg
#
if [ $# -eq 0 ]
then
    echo "$0 : you must supply an integer"
  exit 1
fi

if test $1 -gt 0
then
    echo "$1 is positive"
  else
    echo "$1 is negative"
fi
exit 0
