#!/bin/bash

#using select statements
#select statements are like for loops except they take a list or array and generate
#a selectable menu based on the list. The statement will then iterate after each option
#is selected and perform the indicated action upon the selected option.

declare -a OPTIONS
OPTIONS=(one two three four)
PS3="Select an option: "
select o in "${OPTIONS[@]}"
do
  echo "You selected $o"
done


